katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'catalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from unicodedata import name
from django.urls import path
from todolist.views import show_todolist, register, login_user, logout_user, create_task, delete, options, todolist_ajax, get_todolist_json, add

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create/', create_task, name='create'),
    path('delete/<int:pk>', delete, name='delete'),
    path('options/<int:pk>', options, name='options'),
    path('json/', todolist_ajax, name='show_json'),
    path('get_todolist_json/', get_todolist_json, name='get_todolist_json'),
    path('add/', add, name='add'),

]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user        = models.ForeignKey(User, on_delete=models.CASCADE)
    date        = models.DateField()
    title       = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from todolist.models import Task
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.core import serializers

# Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = Task.objects.filter(user=request.user)
    context = {
    'list_todolist' : data_todolist,
    'username' :  request.user.username,
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

# REGISTER
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

# LOGIN
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)                                                    # Melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))      # Membuat response
            response.set_cookie('last_login', str(datetime.datetime.now()))         # Membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

# LOGOUT
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return redirect('todolist:login')

# CREATE TASK
def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.datetime.now()
        user = request.user
        is_finished = False
        Task.objects.create(title=title, description=description, date=date, user=user, is_finished=is_finished)
        response = HttpResponseRedirect(reverse("todolist:show_todolist")) 
        return response

    return render(request, "create.html")

# DELETE
def delete(request, pk):
    Task.objects.filter(id=pk).delete()
    return redirect('todolist:show_todolist')

# OPTIONS
def options(request, pk):
    data = Task.objects.get(id=pk)
    data.is_finished = not(data.is_finished)
    data.save()
    return redirect('todolist:show_todolist')

# TODOLIST AJAX
@login_required(login_url='/todolist/login/')
def todolist_ajax(request):
    ajax_todolist = Task.objects.filter(user=request.user)
    context = {
    'ajax_todolist' : ajax_todolist,
    'username' :  request.user.username,
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist_ajax.html", context)

# AJAX GET
def get_todolist_json(request):
    data_ajax = Task.objects.filter(user=request.user)

    return HttpResponse(serializers.serialize("json", data_ajax), content_type="application/json")

# ADD TASK MODAL
def add(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.datetime.now()
        user = request.user
        Task.objects.create(title=title, description=description, date=date, user=user)
         
        return HttpResponse(b"CREATED", status=201)

# DELETE TASK JSON
@login_required(login_url='/todolist/login/')
def delete_task(request, id):
    task = Task.objects.filter(user = request.user).get(pk = id)
    task.delete()
    
    return HttpResponse(b"DELETED", status=201)

todolist/templates/create.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}

<!-- BOOTSTRAP -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<!-- Style HTML-->
<style>
    .backgroundCreateTask {
        color: rgb(0, 0, 0); 
        padding: 10px; 
        font-family: 'verdana';
        text-align: center;
        background-image: linear-gradient(90deg, #FA8BFF 0%, #2BD2FF 52%, #2BFF88 90%);
    }

    .tabel {
        padding: 12px 15px; 
        margin-left: auto; 
        margin-right: auto;
    }
    .paddingIsi {
        padding: 5px 15px 10px 10px; 
        text-align: left;
    }
</style>

<body class = "backgroundCreateTask">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <div class = "login vh-100 d-flex justify-content-center align-items-center">
        <div class="card border-primary mb-3" style="width: 30rem; border-radius: 30px; box-shadow: 5px 5px 5px #22302c;">
            <div class="card-body">
            <h1 style="padding: 5px 10px 30px 10px;">📑 Create Task 📑</h1>

            <form method="POST" action="">
                {% csrf_token %}
                <table class="text-start table table-borderless vertical-align form-control">
                    <tr>
                        <td class="paddingIsi">Title :</td>
                        <td><input type="text" name="title" placeholder="Input your Title!" class="form-control"></td>
                    </tr>
                            
                    <tr>
                        <td class="paddingIsi">Description:</td>
                        <td><input type="text" name="description" placeholder="Input your Description!" class="form-control"></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input class="btn login_btn btn btn-primary form-control" type="submit" name="submit" value="Create!"/></td>
                    </tr>
                </table>
            </form>
            </div>
        </div>
    </div>

</body>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<!-- BOOTSTRAP -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<!-- Style HTML-->
<style>
    .backgroundLogin {
        color: rgb(0, 0, 0); 
        padding: 10px; 
        font-family: 'verdana';
        text-align: center;
        background-image: linear-gradient(90deg, #FA8BFF 0%, #2BD2FF 52%, #2BFF88 90%);
    }
    .tabel {
        padding: 12px 15px; 
        margin-left: auto; 
        margin-right: auto;
    }
    .paddingIsi {
        padding: 5px 15px 10px 10px; 
        text-align: left;
    }
</style>

<body class = "backgroundLogin">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <div class = "login vh-100 d-flex justify-content-center align-items-center">
        <div class="card border-primary mb-3" style="width: 30rem; border-radius: 30px; box-shadow: 5px 5px 5px #22302c;">
            <div class="card-body">
                <h1>📱 LOGIN 📱</h1>
                <h6 style="padding: 5px 10px 20px 10px;">a Todolist by Rafi Rasendrya Favian</h6>

                <form method="POST" action="">
                    {% csrf_token %}
                    <table class="text-start table table-borderless vertical-align form-control">
                        <tr>
                            <td class="paddingIsi">👨‍💻Username:</td>
                            <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
                        </tr>
                                
                        <tr>
                            <td class="paddingIsi">🔐Password:</td>
                            <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
                        </tr>

                        <tr>
                            <td></td>
                            <td><input class="btn login_btn btn btn-primary form-control" type="submit" value="Login"></td>
                        </tr>
                    </table>
                </form>

                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <td>{{ message }}</td>
                        {% endfor %}
                    </ul>
                {% endif %}     
                <div style="padding-top: 20px;">   
                Don't have an account🤔? <a href="{% url 'todolist:register' %}">Create Account</a>
                </div> 
            </div>
        </div>
    </div>
</body>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %} 

<!-- BOOTSTRAP -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<!-- Style HTML-->
<style>
    .backgroundRegister {
        color: rgb(0, 0, 0); 
        padding: 10px; 
        font-family: 'verdana';
        background-image: linear-gradient(90deg, #2BFF88 0%, #2BD2FF 52%, #FA8BFF 90%);    
    }
</style>

<body class = "backgroundRegister">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <div class = "login vh-100 d-flex justify-content-center align-items-center">
        <div class="card border-primary mb-3" style="width: 40rem; border-radius: 30px; box-shadow: 5px 5px 5px #22302c;">
            <div class="card-body">
                <h1 class="card-title" style="text-align: center; padding: 5px 10px 20px 10px;">📲 CREATE ACCOUNT 📲</h1>  

                    <form method="POST" >  
                        {% csrf_token %}  
                        <table class="text-start table table-borderless vertical-align form-control" style="font-size: small;">  
                            {{ form.as_table }}  
                            <tr>  
                                <td></td>
                                <td><input class="btn login_btn btn btn-primary form-control" type="submit" name="submit" value="Create!"/></td>  
                            </tr>  
                        </table>  
                    </form>

                {% if messages %}  
                <ul>   
                    {% for message in messages %}  
                        <li>{{ message }}</li>  
                        {% endfor %}  
                </ul>   
                {% endif %}
            </div>
        </div>
    </div>  
</body>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}

<!-- BOOTSTRAP -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
</head>

<!-- Style HTML-->
<style>
    /* JUDUL */
    .mt-5 {
        text-align: center;
        color: rgb(41, 41, 41); 
        padding: 10px; 
        font-family: 'verdana'; 
    }
    .mb-5 {
        text-align: center;
        color: rgb(41, 41, 41); 
        padding: 10px; 
        font-family: 'verdana'; 
    }
    /* BODY TEMPLATE*/
    body {
        font-family: 'verdana'; 
        padding: 15px; 
        background-image: linear-gradient(90deg, #FA8BFF 0%, #2BD2FF 52%, #2BFF88 90%);
        color: #000000;
    }
</style>
<nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" style="text-align: center"href="#">A Todolist by Rafi Rasendrya Favian</a>
    </div>
</nav>
<body>
    <h1 class="mt-5" style="font-size: 10mm;">👋Halooo, {{username}}👋</h1>
    <h4 class="mb-5">😤 Yuk kerjain tugasnya! 😤 </h4>
    
    <div class="row row-cols-md-3 mx-auto" style="width: 100%;">
      
      {% for todo in list_todolist %}
        <div class="col">
            <div class="card border-primary mb-3">
                <div class="card-body">
                    
                    <h3 class="card-title" style="padding-bottom: 5px">{{todo.title}}</h3>
                    <h6 class="card-subtitle">📅{{todo.date}}</h6>
                    <p class="card-text">🚨{{todo.description}}</p>
                    <p class="card-text">
                        {% if todo.is_finished %}
                        ✅ Finished ✅
                        {% else %}
                        ❌ Not Finished ❌
                        {% endif%}
                    </p>
    
                    <p style="text-align: center;">
                        <a style="width: 7rem;" class="btn login_btn btn btn-success form-control" href="options/{{todo.id}}">Status</a>
                        <a style="width: 7rem;" class="btn login_btn btn btn-danger form-control lg" href="delete/{{todo.id}}">Delete</a>
                    </p>
                </div>
            </div>
        </div>
      {% endfor %}
    </div>

    <p style="text-align: center; padding: 20px;">
        <a style="width: 10rem" class="btn login_btn btn btn-dark form-control" href="{% url 'todolist:create' %}">Create</a>
        <a style="width: 10rem" class="btn login_btn btn btn-dark form-control" href="{% url 'todolist:logout' %}">Logout</a>
    </p>

</body> 
{% endblock content %}

todolist/templates/todolist_ajax.html
{% extends 'base.html' %}

{% block content %}



<!-- BOOTSTRAP & AJAX -->
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <!-- Add Ajax -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Add Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
</head>



<!-- Style HTML-->
<style>
    /* JUDUL */
    .mt-5 {
        text-align: center;
        color: rgb(41, 41, 41); 
        padding: 10px; 
        font-family: 'verdana'; 
    }
    .mb-5 {
        text-align: center;
        color: rgb(41, 41, 41); 
        padding: 10px; 
        font-family: 'verdana'; 
    }
    /* BODY TEMPLATE*/
    body {
        font-family: 'verdana'; 
        padding: 15px; 
        background-image: linear-gradient(90deg, #FA8BFF 0%, #2BD2FF 52%, #2BFF88 90%);
        color: #000000;
    }
</style>
<nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" style="text-align: center"href="#">👋Hello, {{username}}</a>
      <button type="button" class="btn btn-outline-light" data-bs-toggle="modal" data-bs-target="#exampleModal" data-bs-whatever="@getbootstrap">Add task</button>
      <a style="width: 7rem" class="btn login_btn btn btn-outline-light form-control" href="{% url 'todolist:logout' %}">Logout</a>
    </div>
</nav>
<body>
    <h4 class="mt-5">😤 Yuk kerjain tugasnya! 😤 </h4>
    
    <!-- MODAL -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">New Task</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>  
                <div class="modal-body">
                    <form id="formtask">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="recipient-name" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="field_title" name="title">
                    </div>
                    <div class="mb-3">
                        <label for="message-text" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="field_desc" name="description"></textarea>
                    </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-success" id="addtaskbutton" data-bs-dismiss="modal">Add</button>
                </div>
            </div>
        </div>
    </div>

    <div class="row row-cols-md-3 mx-auto" style="width: 100%;" id="idRow"></div>

    <script>

        async function getTodolist() {
            return fetch("{% url 'todolist:get_todolist_json' %}").then((res) => res.json())
        }

        async function refreshTodolist() {
            document.getElementById("idRow").innerHTML = ""
            const todolist = await getTodolist()
            let cardAjax = ``
            
            todolist.forEach((todo) => {
            cardAjax += 
            `\n<div class="col">
                <div class="card border-primary mb-3">
                    <div class="card-body">
                        
                        <h3 class="card-title" style="padding-bottom: 5px">${todo.fields.title}</h3>
                        <h6 class="card-subtitle">📅${todo.fields.date}</h6>
                        <p class="card-text">🚨${todo.fields.description}</p>
                        <div class="button">
                            <div class="div_delete_btn">
                                <button class="delete_btn">
                                    <a class="delete_link" onclick="delete_todolist(${todo.pk})">❌ DELETE</a>
                                </button>
                            </div>
                        </div>                
                    </div>
                </div>
            </div>`
            })
        
        document.getElementById("idRow").innerHTML = cardAjax
        }

        function addTodolistModal() {
            fetch("{% url 'todolist:add' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#formtask'))
            }).then(refreshTodolist)
            return false
        }

        function delete_todolist(id) {
            console.log(id)
            let url = "/todolist/delete/" + id;
            fetch(url)
        }

        document.getElementById("addtaskbutton").onclick = addTodolistModal


        refreshTodolist()

    </script>

</body> 
{% endblock content %}